name: Deploy Darkweb App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/darkweb
            echo "Pulling latest changes..."
            git reset --hard
            git pull origin main

            echo "Installing backend dependencies..."
            cd backend
            npm install

            echo "Restarting backend..."
            pm2 stop darkweb-backend || true
            PORT=4001 pm2 start server.js --name darkweb-backend

            echo "Installing frontend dependencies..."
            cd ../frontend
            npm install
            npm run build

            echo "Restarting frontend..."
            pm2 stop darkweb-frontend || true
            PORT=4000 pm2 start npm --name darkweb-frontend -- start

            echo "Saving PM2 state..."
            pm2 save
